---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-operator
  template:
    metadata:
      labels:
        app: rabbitmq-operator
    spec:
      serviceAccountName: rabbitmq-operator
      containers:
        - name: rabbitmq-operator
          image: 716309063777.dkr.ecr.us-east-1.amazonaws.com/rabbitmq-operator:latest
          imagePullPolicy: Always
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SENTRY_DSN
              value: "https://983d2bf5d8f247e98b89d179b737a48d:f3133ece803044fa8491775da2d56cf5@sentry.tools.improvado.io/37"
            - name: OPERATOR_NAME
              value: "rabbitmq-operator"
            - name: WATCH_NAMESPACE
              value: "messaging"

# create service for deployment

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-operator
spec:
  selector:
    app: rabbitmq-operator
  ports:
  - port: 80
